In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('retail_data.csv')
df.head()

,Month,Enquiry Date,Enquiry Id,Allocation Status,Status,State,City,Pincode,Type of Project,No of Windows,...,Second Action-Call Status.1,Remarks,Price Per Sft,Benefits,Aesthetics,Reduce Street Noise,Low Maintenance,Monsoon Proof,Better Lighting,Reduce AC Energy Cost
0,April'16,02-Apr-16,EC02041646800,Dealer,Won,TAMILNADU,CHENNAI,600008,Renovation,6 to 10,...,NaN,NaN,1105,Aesthetics & Street Noise,1.0,1.0,0.0,0.0,0.0,0.0
1,April'16,08-Apr-16,EC08041647157,Dealer,Lost,TAMILNADU,CHENNAI,600042,New Construction,6 to 10,...,NaN,Price Issue,985,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,April'16,08-Apr-16,EC08041647130,Dealer,Lost,TAMILNADU,CHENNAI,600015,New Construction,1 to 5,...,NaN,Delivery Issue,918,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,April'16,09-Apr-16,EC09041647202,Direct,Lost,TAMILNADU,KANCHIPURAM,600075,New Construction,21 to 40,...,NaN,Price Issue,919,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,April'16,11-Apr-16,EC11041647360,Direct,Won,TAMILNADU,CHENNAI,600041,Renovation,6 to 10,...,NaN,NaN,1350,Reduce AC Energy Cost,0.0,0.0,0.0,0.0,0.0,1.0

In [19]:
df['Status'].value_counts()

Lost    176
Won      53
Name: Status, dtype: int64

In [24]:
df.groupby('Dealer Name').count()['Status']

Dealer Name
Direct        63
ITP           14
OXXO          20
Pearlson       9
Rajtechnis    15
Sunbird       36
Windoors      45
Winfratech    20
pearlson       7
Name: Status, dtype: int64

In [46]:
df1=df[['Dealer Name','Remarks','Status']]
df1.dropna(inplace=True)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [47]:
df1.shape

(171, 3)

In [48]:
df1.groupby('Remarks').count()

                               Dealer Name  Status
Remarks
Budget Constraint                       26      26
Delivery Issue                           3       3
Delivery Issve                           1       1
Design Infeasibe My                      1       1
Design Infeasibility                    23      23
Design Not Feasible                      1       1
No Requirement                           1       1
No Requirement-Awareness Call            1       1
No Requirment                            2       2
Others                                   1       1
Price Issue                            103     103
Price issue                              7       7
Service Infeasibility                    1       1

In [51]:
s=df1.groupby(['Dealer Name','Remarks']).count()

In [53]:
s

                                           Status
Dealer Name Remarks
Direct      Budget Constraint                   5
            Delivery Issue                      1
            Design Infeasibility                3
            No Requirement                      1
            No Requirment                       1
            Price Issue                        22
            Price issue                         4
            Service Infeasibility               1
ITP         Budget Constraint                   2
            Design Infeasibility                3
            Price Issue                         9
OXXO        Budget Constraint                   2
            Design Infeasibility                3
            Design Not Feasible                 1
            Price Issue                         8
            Price issue                         1
Pearlson    Budget Constraint                   5
            Delivery Issue                      1
            Price Issue                         2
Rajtechnis  Budget Constraint                   1
            No Requirement-Awareness Call       1
            Price Issue                         9
            Price issue                         1
Sunbird     Budget Constraint                   5
            Delivery Issue                      1
            Delivery Issve                      1
            Design Infeasibility                5
            Price Issue                        12
            Price issue                         1
Windoors    Budget Constraint                   4
            Design Infeasibe My                 1
            Design Infeasibility                1
            Price Issue                        31
Winfratech  Budget Constraint                   1
            Design Infeasibility                6
            No Requirment                       1
            Price Issue                        10
pearlson    Budget Constraint                   1
            Design Infeasibility                2
            Others                              1